### ISSUE TITLE
Sort media ignoring "The"

### ISSUE THREAD

**Issue by demonspork** [freezy/android-xbmcremote#11]
Currently in the list of Movies, TV Shows, and Music in the app everything is arranged alphabetically regardless of it starting with the word "The". This results in shows being in unexpected positions as well as a large chunk of movies being in the T section that are not normally there.

**Comment by demonspork** [comment]
This issue could be closed if Pull Request 12 (https://github.com/freezy/android-xbmcremote/pull/12) is accepted

**Comment by tombriden** [comment]
not an issue in current version
