### ISSUE TITLE
NullPointerException on Android Ice Cream Sandwich 4.0.3

### ISSUE THREAD

**Issue by gregs007** [freezy/android-xbmcremote#16]
After upgrade from Gingerbraead to Ice Cream Sandwich (4.0.3), kernel 3.0.8.gb55e9ac android-build@apa28 #1, build number IML74K on a Nexus S I9020XXKI1 (I9020T), get consistent NullPointerExecption on every button press. Standard remote control sometimes works, but all library functions do not work since upgrade. Also, app gets stuck in force close loop sometimes.

**Comment by freezy** [comment]
Thanks, but most discussion already took place here: http://code.google.com/p/android-xbmcremote/issues/detail?id=581

Will close this once it's resolved. Cheers!

**Comment by freezy** [comment]
Solved and ready to release.
