### ISSUE TITLE
IO Exception when starting the remote control

### ISSUE THREAD

**Issue by jmdacruz** [freezy/android-xbmcremote#49]
This issue was previously documented [here](http://code.google.com/p/android-xbmcremote/issues/detail?id=670) (I'm not the original reporter). Resubmitting on github, since I cannot find the issue here.

_Including the description of the original bug below_

**What steps will reproduce the problem?**
1. Start XBMC Remote
2. Start remote control (sometime error even without starting remote control)
3. Error message shows:
I/O Exception (java.io.FileNotFoundException)
http://192.168.2.30:8080/
xbmcCmds/xbmcHttp?command=GetSystemInfo(120)

**What is the expected output? What do you see instead?**
No error message.

**What version of XBMC Remote are you using?**
v0.8.8-beta1 build 808

**Which Android device are you using (and which ROM, if custom)?**
JB

**Comment by kevinkhill** [comment]
I am having this same issue and I have read it is because the HTTP API is being depreciated, which means our android xbmc remotes might stop working all together unless they switch it all over the the JSON RPC API. (which I hope they do). The android xbmc remote is long overdue for an update.

**Comment by freezy** [comment]
Working on it: https://github.com/freezy/xbmc-jsonrpclib-android-generator

**Comment by kevinkhill** [comment]
Hooray!

**Comment by lafriks** [comment]
Looks like with xbmc 12 beta 1 it's not working at all now... Would be great if this could  be released in alpha or beta state soon

**Comment by dukestraykker** [comment]
I came here looking for the same answers for 12 beta 1. I just found that even though the error pops up at program start, if you click ok, then click remote control in the menu, the error will pop up again. Hit ok again, and then you are able to use the remote just like before, regardless of the two earlier errors. Can anyone else test this and confirm the same?

**Comment by tthomas48** [comment]
I plan on working on this over Thanksgiving. Didn't realize we were at Beta
1. I should have gotten my list of missing API calls in...

**Comment by freezy** [comment]
Cheers! Looking forward to it.

**Comment by balg** [comment]
Yes, after closing of the error messages, the remote control works fine. :) Thank you!

**Comment by freezy** [comment]
Merged Tim's code and added new error message in case JSON-RPC is not enabled in host settings.

**Comment by brentspell** [comment]
Love the app. Any chance of this geting to Google Play soon?

**Comment by hetsch** [comment]
+1 for google play.
Thank's a lot for this app...

**Comment by freezy** [comment]
Yeah we'll release the update on Google Play with the final release of Frodo.

**Comment by konkere** [comment]
Frodo is here!
freezy, where is update on gplay?

**Comment by freezy** [comment]
Coming.
